steps:
  # Run migration with Cloud SQL Proxy in the same container
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        apt-get update && apt-get install -y postgresql-client wget

        echo "Downloading Cloud SQL Proxy..."
        wget -q https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.1/cloud-sql-proxy.linux.amd64 -O /cloud-sql-proxy
        chmod +x /cloud-sql-proxy

        echo "Starting Cloud SQL Proxy..."
        /cloud-sql-proxy gen-lang-client-0145804280:asia-east1:golden-dragon-db --port=5432 &
        sleep 5

        echo "Running database migrations..."

        # Add pictureUrl to Customer table
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "ALTER TABLE \"Customer\" ADD COLUMN IF NOT EXISTS \"pictureUrl\" TEXT;"

        # Ensure CrmCustomer table exists
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "
        CREATE TABLE IF NOT EXISTS \"CrmCustomer\" (
          \"id\" TEXT NOT NULL,
          \"customerCode\" TEXT NOT NULL,
          \"name\" TEXT NOT NULL,
          \"phone\" TEXT,
          \"email\" TEXT,
          \"address\" TEXT,
          \"company\" TEXT,
          \"notes\" TEXT,
          \"metadata\" JSONB,
          \"externalId\" TEXT,
          \"lastSyncAt\" TIMESTAMP(3),
          \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
          \"updatedAt\" TIMESTAMP(3) NOT NULL,
          CONSTRAINT \"CrmCustomer_pkey\" PRIMARY KEY (\"id\")
        );"

        # Add unique constraint if not exists
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "
        CREATE UNIQUE INDEX IF NOT EXISTS \"CrmCustomer_customerCode_key\" ON \"CrmCustomer\"(\"customerCode\");"

        # Add indexes
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "
        CREATE INDEX IF NOT EXISTS \"CrmCustomer_customerCode_idx\" ON \"CrmCustomer\"(\"customerCode\");
        CREATE INDEX IF NOT EXISTS \"CrmCustomer_phone_idx\" ON \"CrmCustomer\"(\"phone\");
        CREATE INDEX IF NOT EXISTS \"CrmCustomer_email_idx\" ON \"CrmCustomer\"(\"email\");"

        # Add crmCustomerId to Customer table if not exists
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "ALTER TABLE \"Customer\" ADD COLUMN IF NOT EXISTS \"crmCustomerId\" TEXT;"

        # Add foreign key if not exists
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "
        DO \$\$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Customer_crmCustomerId_fkey') THEN
            ALTER TABLE \"Customer\" ADD CONSTRAINT \"Customer_crmCustomerId_fkey\" FOREIGN KEY (\"crmCustomerId\") REFERENCES \"CrmCustomer\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE;
          END IF;
        END
        \$\$;"

        # Add index on crmCustomerId
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "
        CREATE INDEX IF NOT EXISTS \"Customer_crmCustomerId_idx\" ON \"Customer\"(\"crmCustomerId\");"

        echo "Checking Customer columns:"
        PGPASSWORD=GoldenDragon2024! psql -h 127.0.0.1 -p 5432 -U postgres -d golden_dragon -c "SELECT column_name FROM information_schema.columns WHERE table_name='Customer' ORDER BY ordinal_position;"

        echo "Migration completed!"

options:
  logging: CLOUD_LOGGING_ONLY
